// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace iWEB_CRM_Tests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Verify that the mailing label field has data in it after creating Individual
        /// </summary>
        public void Assert_MailingLabel_On_Ind_Add()
        {
            #region Variable Declarations
            HtmlSpan uIF1_cxa_mailing_labelPane = this.UICRMOverviewOverviewaWindow.UICRMIndividualsMrRyanDocument.UIF1_cxa_mailing_labelPane;
            #endregion

            // Verify that the 'InnerText' property of 'F1_cxa_mailing_label_html' pane is not equal to 'null'
            Assert.IsNotNull(uIF1_cxa_mailing_labelPane.InnerText, "InnerText for new Individual is null");
        }
        
        /// <summary>
        /// Add basic individual record w/ baseline fields
        /// </summary>
        public void iWEB_Add_Individual_Ryan_Bingham()
        {
            #region Variable Declarations
            HtmlImage uIAbilalogoimageImage = this.UICRMOverviewOverviewaWindow.UICRMOverviewOverviewaDocument.UINavBarContainerPane.UIAbilalogoimageImage;
            HtmlHyperlink uIAddHyperlink = this.UICRMOverviewOverviewaWindow.UICRMOverviewOverviewaDocument.UIAddHyperlink;
            HtmlComboBox uIInd_prf_codeComboBox = this.UICRMOverviewOverviewaWindow.UIAddIndividualDocument.UIInd_prf_codeComboBox;
            HtmlEdit uIFirstnameEdit = this.UICRMOverviewOverviewaWindow.UIAddIndividualDocument.UIFirstnameEdit;
            HtmlEdit uILastnameEdit = this.UICRMOverviewOverviewaWindow.UIAddIndividualDocument.UILastnameEdit;
            HtmlComboBox uIIndividualtypeComboBox = this.UICRMOverviewOverviewaWindow.UIAddIndividualDocument.UIIndividualtypeComboBox;
            HtmlEdit uITitleEdit = this.UICRMOverviewOverviewaWindow.UIAddIndividualDocument.UITitleEdit;
            HtmlEdit uIEmailaddressEdit = this.UICRMOverviewOverviewaWindow.UIAddIndividualDocument.UIEmailaddressEdit;
            HtmlEdit uIAddressline1Edit = this.UICRMOverviewOverviewaWindow.UIAddIndividualDocument.UIAddressline1Edit;
            HtmlEdit uICityEdit = this.UICRMOverviewOverviewaWindow.UIAddIndividualDocument.UICityEdit;
            HtmlComboBox uIAdr_stateComboBox = this.UICRMOverviewOverviewaWindow.UIAddIndividualDocument.UIAdr_stateComboBox;
            HtmlEdit uIPostalcodeEdit = this.UICRMOverviewOverviewaWindow.UIAddIndividualDocument.UIPostalcodeEdit;
            HtmlEdit uICountyEdit = this.UICRMOverviewOverviewaWindow.UIAddIndividualDocument.UICountyEdit;
            HtmlComboBox uICountryComboBox = this.UICRMOverviewOverviewaWindow.UIAddIndividualDocument.UICountryComboBox;
            HtmlDiv uIDesignedDivPane = this.UICRMOverviewOverviewaWindow.UIAddIndividualDocument.UIDesignedDivPane;
            HtmlEdit uIPhonenumberEdit = this.UICRMOverviewOverviewaWindow.UIAddIndividualDocument.UIPhonenumberEdit;
            HtmlComboBox uIContactbyComboBox = this.UICRMOverviewOverviewaWindow.UIAddIndividualDocument.UIContactbyComboBox;
            HtmlCheckBox uIPhoneCheckBox = this.UICRMOverviewOverviewaWindow.UIAddIndividualDocument.UIPhoneCheckBox;
            HtmlComboBox uIKeyComboBox = this.UICRMOverviewOverviewaWindow.UIAddIndividualDocument.UIKeyComboBox;
            HtmlEdit uIAddressline1Edit2 = this.UICRMOverviewOverviewaWindow.UIAddIndividualDocument.UIAddressline1Edit2;
            HtmlEdit uICityEdit1 = this.UICRMOverviewOverviewaWindow.UIAddIndividualDocument.UICityEdit1;
            HtmlComboBox uIAd2__adr_stateComboBox = this.UICRMOverviewOverviewaWindow.UIAddIndividualDocument.UIAd2__adr_stateComboBox;
            HtmlDiv uIDesignedSubDiv_DESIGPane = this.UICRMOverviewOverviewaWindow.UIAddIndividualDocument.UIDesignedSubDiv_DESIGPane;
            HtmlEdit uIPostalcodeEdit1 = this.UICRMOverviewOverviewaWindow.UIAddIndividualDocument.UIPostalcodeEdit1;
            HtmlEdit uICountyEdit1 = this.UICRMOverviewOverviewaWindow.UIAddIndividualDocument.UICountyEdit1;
            HtmlComboBox uICountryComboBox1 = this.UICRMOverviewOverviewaWindow.UIAddIndividualDocument.UICountryComboBox1;
            HtmlSpan uICst_regexPane = this.UICRMOverviewOverviewaWindow.UIAddIndividualDocument.UICst_regexPane;
            HtmlComboBox uITypeComboBox = this.UICRMOverviewOverviewaWindow.UIAddIndividualDocument.UITypeComboBox;
            HtmlEdit uIPhonenumberEdit1 = this.UICRMOverviewOverviewaWindow.UIAddIndividualDocument.UIPhonenumberEdit1;
            HtmlEdit uINewpasswordEdit = this.UICRMOverviewOverviewaWindow.UIAddIndividualDocument.UINewpasswordEdit;
            HtmlEdit uIConfirmnewpasswordEdit = this.UICRMOverviewOverviewaWindow.UIAddIndividualDocument.UIConfirmnewpasswordEdit;
            HtmlCheckBox uIForceusertochangepasCheckBox = this.UICRMOverviewOverviewaWindow.UIAddIndividualDocument.UIForceusertochangepasCheckBox;
            HtmlInputButton uISaveButton = this.UICRMOverviewOverviewaWindow.UIAddIndividualDocument.UISaveButton;
            HtmlSpan uIF1_cxa_mailing_labelPane = this.UICRMOverviewOverviewaWindow.UICRMIndividualsMrRyanDocument.UIF1_cxa_mailing_labelPane;
            #endregion

            // Click 'Abila logo image' image
            Mouse.Click(uIAbilalogoimageImage, new Point(39, 19));

            // Click 'Add' link
            Mouse.Click(uIAddHyperlink, new Point(12, 10));

            // Select 'Mr.' in 'ind_prf_code' combo box
            uIInd_prf_codeComboBox.SelectedItem = this.iWEB_Add_Individual_Ryan_BinghamParams.UIInd_prf_codeComboBoxSelectedItem;

            // Type 'Ryan' in 'first name' text box
            uIFirstnameEdit.Text = this.iWEB_Add_Individual_Ryan_BinghamParams.UIFirstnameEditText;

            // Type 'Bingham' in 'last name' text box
            uILastnameEdit.Text = this.iWEB_Add_Individual_Ryan_BinghamParams.UILastnameEditText;

            // Select 'General' in 'individual type:' combo box
            uIIndividualtypeComboBox.SelectedItem = this.iWEB_Add_Individual_Ryan_BinghamParams.UIIndividualtypeComboBoxSelectedItem;

            // Type 'Tester' in 'title' text box
            uITitleEdit.Text = this.iWEB_Add_Individual_Ryan_BinghamParams.UITitleEditText;

            // Type 'ryan.bingham@test.com' in 'e-mail address' text box
            uIEmailaddressEdit.Text = this.iWEB_Add_Individual_Ryan_BinghamParams.UIEmailaddressEditText;

            // Type '1234 Test St' in 'address line 1' text box
            uIAddressline1Edit.Text = this.iWEB_Add_Individual_Ryan_BinghamParams.UIAddressline1EditText;

            // Type '{Tab}' in 'address line 1' text box
            Keyboard.SendKeys(uIAddressline1Edit, this.iWEB_Add_Individual_Ryan_BinghamParams.UIAddressline1EditSendKeys, ModifierKeys.None);

            // Type 'Austin' in 'city' text box
            uICityEdit.Text = this.iWEB_Add_Individual_Ryan_BinghamParams.UICityEditText;

            // Type '{Tab}' in 'city' text box
            Keyboard.SendKeys(uICityEdit, this.iWEB_Add_Individual_Ryan_BinghamParams.UICityEditSendKeys, ModifierKeys.None);

            // Select 'Texas' in 'adr_state' combo box
            uIAdr_stateComboBox.SelectedItem = this.iWEB_Add_Individual_Ryan_BinghamParams.UIAdr_stateComboBoxSelectedItem;

            // Type '78701' in 'postal code' text box
            uIPostalcodeEdit.Text = this.iWEB_Add_Individual_Ryan_BinghamParams.UIPostalcodeEditText;

            // Type 'Travis' in 'county' text box
            uICountyEdit.Text = this.iWEB_Add_Individual_Ryan_BinghamParams.UICountyEditText;

            // Select 'UNITED STATES' in 'country:' combo box
            uICountryComboBox.SelectedItem = this.iWEB_Add_Individual_Ryan_BinghamParams.UICountryComboBoxSelectedItem;

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover 'DesignedDiv' pane at (1, 1)
            Mouse.Hover(uIDesignedDivPane, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Type '512-555-1212' in 'phone number' text box
            uIPhonenumberEdit.Text = this.iWEB_Add_Individual_Ryan_BinghamParams.UIPhonenumberEditText;

            // Select 'E-Mail' in 'contact by:' combo box
            uIContactbyComboBox.SelectedItem = this.iWEB_Add_Individual_Ryan_BinghamParams.UIContactbyComboBoxSelectedItem;

            // Select 'phone' check box
            uIPhoneCheckBox.Checked = this.iWEB_Add_Individual_Ryan_BinghamParams.UIPhoneCheckBoxChecked;

            // Select 'Home' in 'key' combo box
            uIKeyComboBox.SelectedItem = this.iWEB_Add_Individual_Ryan_BinghamParams.UIKeyComboBoxSelectedItem;

            // Type '5678 Test St' in 'address line 1' text box
            uIAddressline1Edit2.Text = this.iWEB_Add_Individual_Ryan_BinghamParams.UIAddressline1Edit2Text;

            // Type 'Austin' in 'city' text box
            uICityEdit1.Text = this.iWEB_Add_Individual_Ryan_BinghamParams.UICityEdit1Text;

            // Select 'Texas' in 'ad2__adr_state' combo box
            uIAd2__adr_stateComboBox.SelectedItem = this.iWEB_Add_Individual_Ryan_BinghamParams.UIAd2__adr_stateComboBoxSelectedItem;

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover 'DesignedSubDiv_DESIGNEDSUBFORM_1' pane at (1, 1)
            Mouse.Hover(uIDesignedSubDiv_DESIGPane, new Point(1, 1));

            // Mouse hover 'postal code' text box at (1, 1)
            Mouse.Hover(uIPostalcodeEdit1, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Type '78735' in 'postal code' text box
            uIPostalcodeEdit1.Text = this.iWEB_Add_Individual_Ryan_BinghamParams.UIPostalcodeEdit1Text;

            // Click 'county' text box
            Mouse.Click(uICountyEdit1, new Point(117, 10));

            // Type '78701' in 'postal code' text box
            uIPostalcodeEdit.Text = this.iWEB_Add_Individual_Ryan_BinghamParams.UIPostalcodeEditText1;

            // Type '{Tab}' in 'postal code' text box
            Keyboard.SendKeys(uIPostalcodeEdit, this.iWEB_Add_Individual_Ryan_BinghamParams.UIPostalcodeEditSendKeys, ModifierKeys.None);

            // Select 'UNITED STATES' in 'country:' combo box
            uICountryComboBox1.SelectedItem = this.iWEB_Add_Individual_Ryan_BinghamParams.UICountryComboBox1SelectedItem;

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover 'DesignedDiv' pane at (1, 1)
            Mouse.Hover(uIDesignedDivPane, new Point(1, 1));

            // Mouse hover 'cst_regex' pane at (1, 1)
            Mouse.Hover(uICst_regexPane, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Select 'Home' in 'type:' combo box
            uITypeComboBox.SelectedItem = this.iWEB_Add_Individual_Ryan_BinghamParams.UITypeComboBoxSelectedItem;

            // Type '512-555-1313' in 'phone number' text box
            uIPhonenumberEdit1.Text = this.iWEB_Add_Individual_Ryan_BinghamParams.UIPhonenumberEdit1Text;

            // Type '********' in 'new password' text box
            uINewpasswordEdit.Password = this.iWEB_Add_Individual_Ryan_BinghamParams.UINewpasswordEditPassword;

            // Type '{Tab}' in 'new password' text box
            Keyboard.SendKeys(uINewpasswordEdit, this.iWEB_Add_Individual_Ryan_BinghamParams.UINewpasswordEditSendKeys, ModifierKeys.None);

            // Type '********' in 'confirm new password' text box
            uIConfirmnewpasswordEdit.Password = this.iWEB_Add_Individual_Ryan_BinghamParams.UIConfirmnewpasswordEditPassword;

            // Select 'force user to change password?' check box
            uIForceusertochangepasCheckBox.Checked = this.iWEB_Add_Individual_Ryan_BinghamParams.UIForceusertochangepasCheckBoxChecked;

            // Click 'Save' button
            Mouse.Click(uISaveButton, new Point(13, 18));

            // Click 'F1_cxa_mailing_label_html' pane
            Mouse.Click(uIF1_cxa_mailing_labelPane, new Point(41, 4));
        }
        
        #region Properties
        public virtual iWEB_Add_Individual_Ryan_BinghamParams iWEB_Add_Individual_Ryan_BinghamParams
        {
            get
            {
                if ((this.miWEB_Add_Individual_Ryan_BinghamParams == null))
                {
                    this.miWEB_Add_Individual_Ryan_BinghamParams = new iWEB_Add_Individual_Ryan_BinghamParams();
                }
                return this.miWEB_Add_Individual_Ryan_BinghamParams;
            }
        }
        
        public UICRMOverviewOverviewaWindow UICRMOverviewOverviewaWindow
        {
            get
            {
                if ((this.mUICRMOverviewOverviewaWindow == null))
                {
                    this.mUICRMOverviewOverviewaWindow = new UICRMOverviewOverviewaWindow();
                }
                return this.mUICRMOverviewOverviewaWindow;
            }
        }
        #endregion
        
        #region Fields
        private iWEB_Add_Individual_Ryan_BinghamParams miWEB_Add_Individual_Ryan_BinghamParams;
        
        private UICRMOverviewOverviewaWindow mUICRMOverviewOverviewaWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'iWEB_Add_Individual_Ryan_Bingham'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class iWEB_Add_Individual_Ryan_BinghamParams
    {
        
        #region Fields
        /// <summary>
        /// Select 'Mr.' in 'ind_prf_code' combo box
        /// </summary>
        public string UIInd_prf_codeComboBoxSelectedItem = "Mr.";
        
        /// <summary>
        /// Type 'Ryan' in 'first name' text box
        /// </summary>
        public string UIFirstnameEditText = "Ryan";
        
        /// <summary>
        /// Type 'Bingham' in 'last name' text box
        /// </summary>
        public string UILastnameEditText = "Bingham";
        
        /// <summary>
        /// Select 'General' in 'individual type:' combo box
        /// </summary>
        public string UIIndividualtypeComboBoxSelectedItem = "General";
        
        /// <summary>
        /// Type 'Tester' in 'title' text box
        /// </summary>
        public string UITitleEditText = "Tester";
        
        /// <summary>
        /// Type 'ryan.bingham@test.com' in 'e-mail address' text box
        /// </summary>
        public string UIEmailaddressEditText = "ryan.bingham@test.com";
        
        /// <summary>
        /// Type '1234 Test St' in 'address line 1' text box
        /// </summary>
        public string UIAddressline1EditText = "1234 Test St";
        
        /// <summary>
        /// Type '{Tab}' in 'address line 1' text box
        /// </summary>
        public string UIAddressline1EditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'Austin' in 'city' text box
        /// </summary>
        public string UICityEditText = "Austin";
        
        /// <summary>
        /// Type '{Tab}' in 'city' text box
        /// </summary>
        public string UICityEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Select 'Texas' in 'adr_state' combo box
        /// </summary>
        public string UIAdr_stateComboBoxSelectedItem = "Texas";
        
        /// <summary>
        /// Type '78701' in 'postal code' text box
        /// </summary>
        public string UIPostalcodeEditText = "78701";
        
        /// <summary>
        /// Type 'Travis' in 'county' text box
        /// </summary>
        public string UICountyEditText = "Travis";
        
        /// <summary>
        /// Select 'UNITED STATES' in 'country:' combo box
        /// </summary>
        public string UICountryComboBoxSelectedItem = "UNITED STATES";
        
        /// <summary>
        /// Type '512-555-1212' in 'phone number' text box
        /// </summary>
        public string UIPhonenumberEditText = "512-555-1212";
        
        /// <summary>
        /// Select 'E-Mail' in 'contact by:' combo box
        /// </summary>
        public string UIContactbyComboBoxSelectedItem = "E-Mail";
        
        /// <summary>
        /// Select 'phone' check box
        /// </summary>
        public bool UIPhoneCheckBoxChecked = true;
        
        /// <summary>
        /// Select 'Home' in 'key' combo box
        /// </summary>
        public string UIKeyComboBoxSelectedItem = "Home";
        
        /// <summary>
        /// Type '5678 Test St' in 'address line 1' text box
        /// </summary>
        public string UIAddressline1Edit2Text = "5678 Test St";
        
        /// <summary>
        /// Type 'Austin' in 'city' text box
        /// </summary>
        public string UICityEdit1Text = "Austin";
        
        /// <summary>
        /// Select 'Texas' in 'ad2__adr_state' combo box
        /// </summary>
        public string UIAd2__adr_stateComboBoxSelectedItem = "Texas";
        
        /// <summary>
        /// Type '78735' in 'postal code' text box
        /// </summary>
        public string UIPostalcodeEdit1Text = "78735";
        
        /// <summary>
        /// Type '78701' in 'postal code' text box
        /// </summary>
        public string UIPostalcodeEditText1 = "78701";
        
        /// <summary>
        /// Type '{Tab}' in 'postal code' text box
        /// </summary>
        public string UIPostalcodeEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Select 'UNITED STATES' in 'country:' combo box
        /// </summary>
        public string UICountryComboBox1SelectedItem = "UNITED STATES";
        
        /// <summary>
        /// Select 'Home' in 'type:' combo box
        /// </summary>
        public string UITypeComboBoxSelectedItem = "Home";
        
        /// <summary>
        /// Type '512-555-1313' in 'phone number' text box
        /// </summary>
        public string UIPhonenumberEdit1Text = "512-555-1313";
        
        /// <summary>
        /// Type '********' in 'new password' text box
        /// </summary>
        public string UINewpasswordEditPassword = "MFX9pInYa91KyLzdtTLvRHzjoH1+C9v/";
        
        /// <summary>
        /// Type '{Tab}' in 'new password' text box
        /// </summary>
        public string UINewpasswordEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'confirm new password' text box
        /// </summary>
        public string UIConfirmnewpasswordEditPassword = "MFX9pInYa91KyLzdtTLvRHzjoH1+C9v/";
        
        /// <summary>
        /// Select 'force user to change password?' check box
        /// </summary>
        public bool UIForceusertochangepasCheckBoxChecked = true;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UICRMOverviewOverviewaWindow : BrowserWindow
    {
        
        public UICRMOverviewOverviewaWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "CRM | Overview | Overview and Setup";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("CRM | Overview | Overview and Setup");
            this.WindowTitles.Add("Add - Individual");
            this.WindowTitles.Add("CRM | Individuals | Mr. Ryan Bingham");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UICRMOverviewOverviewaDocument UICRMOverviewOverviewaDocument
        {
            get
            {
                if ((this.mUICRMOverviewOverviewaDocument == null))
                {
                    this.mUICRMOverviewOverviewaDocument = new UICRMOverviewOverviewaDocument(this);
                }
                return this.mUICRMOverviewOverviewaDocument;
            }
        }
        
        public UIAddIndividualDocument UIAddIndividualDocument
        {
            get
            {
                if ((this.mUIAddIndividualDocument == null))
                {
                    this.mUIAddIndividualDocument = new UIAddIndividualDocument(this);
                }
                return this.mUIAddIndividualDocument;
            }
        }
        
        public UICRMIndividualsMrRyanDocument UICRMIndividualsMrRyanDocument
        {
            get
            {
                if ((this.mUICRMIndividualsMrRyanDocument == null))
                {
                    this.mUICRMIndividualsMrRyanDocument = new UICRMIndividualsMrRyanDocument(this);
                }
                return this.mUICRMIndividualsMrRyanDocument;
            }
        }
        #endregion
        
        #region Fields
        private UICRMOverviewOverviewaDocument mUICRMOverviewOverviewaDocument;
        
        private UIAddIndividualDocument mUIAddIndividualDocument;
        
        private UICRMIndividualsMrRyanDocument mUICRMIndividualsMrRyanDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UICRMOverviewOverviewaDocument : HtmlDocument
    {
        
        public UICRMOverviewOverviewaDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = "BodyTag";
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "CRM | Overview | Overview and Setup";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/iWeb/Forms/DynamicProfile.aspx";
            //this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://nf.testacfe.com/iWeb/Forms/DynamicProfile.aspx?key=00000000-0000-0000-000" +
            //    "0-000000000000&FormKey=26ca3bb2-8061-45f5-bd0b-5438abd41a59&ItemKey=8a71d077-5bc" +
            //    "0-43c8-810a-478fb4704903&LinkKey=66d89b0b-eaae-4853-90c3-238d4531bd1a&Tab=CRM&Ta" +
            //    "bItem=Overview";
            this.WindowTitles.Add("CRM | Overview | Overview and Setup");
            #endregion
        }
        
        #region Properties
        public UINavBarContainerPane UINavBarContainerPane
        {
            get
            {
                if ((this.mUINavBarContainerPane == null))
                {
                    this.mUINavBarContainerPane = new UINavBarContainerPane(this);
                }
                return this.mUINavBarContainerPane;
            }
        }
        
        public HtmlHyperlink UIAddHyperlink
        {
            get
            {
                if ((this.mUIAddHyperlink == null))
                {
                    this.mUIAddHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIAddHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "F1_HYPERLINK_4";
                    this.mUIAddHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIAddHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIAddHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Add";
                    this.mUIAddHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/iWeb/Forms/DynamicEdit.aspx";
                    this.mUIAddHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIAddHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "/iWeb/Forms/DynamicEdit.aspx?Action=Add&FormKey=25cad8ad-0" +
                        "921-4b50-92ed-f8d36f1fad7f&ItemKey=649d1a9d-ca93-4dd8-b5b5-aa00e10946b0&tab=crm&" +
                        "tabitem=individuals";
                    this.mUIAddHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "tabTXT";
                    this.mUIAddHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "tabindex=\"7\" class=\"tabTXT\" id=\"F1_HYPER";
                    this.mUIAddHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "77";
                    this.mUIAddHyperlink.WindowTitles.Add("CRM | Overview | Overview and Setup");
                    #endregion
                }
                return this.mUIAddHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private UINavBarContainerPane mUINavBarContainerPane;
        
        private HtmlHyperlink mUIAddHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UINavBarContainerPane : HtmlDiv
    {
        
        public UINavBarContainerPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "NavBarContainer";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Jeff Miller\r\n\r\nMy Profile\r\n\r\n\r\nMy Prefer";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "container-fluid";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"container-fluid\" id=\"NavBarContainer\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "4";
            this.WindowTitles.Add("CRM | Overview | Overview and Setup");
            #endregion
        }
        
        #region Properties
        public HtmlImage UIAbilalogoimageImage
        {
            get
            {
                if ((this.mUIAbilalogoimageImage == null))
                {
                    this.mUIAbilalogoimageImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUIAbilalogoimageImage.SearchProperties[HtmlImage.PropertyNames.Id] = null;
                    this.mUIAbilalogoimageImage.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUIAbilalogoimageImage.SearchProperties[HtmlImage.PropertyNames.Alt] = "Abila logo image";
                    this.mUIAbilalogoimageImage.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/iWeb/images/masthead-logo.png";
                    this.mUIAbilalogoimageImage.FilterProperties[HtmlImage.PropertyNames.Src] = "/iWeb/images/masthead-logo.png";
                    this.mUIAbilalogoimageImage.FilterProperties[HtmlImage.PropertyNames.LinkAbsolutePath] = "/iWeb/AbandonSession.aspx";
                    this.mUIAbilalogoimageImage.FilterProperties[HtmlImage.PropertyNames.Href] = "/iWeb/AbandonSession.aspx";
                    this.mUIAbilalogoimageImage.FilterProperties[HtmlImage.PropertyNames.Class] = null;
                    this.mUIAbilalogoimageImage.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "alt=\"Abila logo image\" src=\"../images/ma";
                    this.mUIAbilalogoimageImage.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "1";
                    this.mUIAbilalogoimageImage.WindowTitles.Add("CRM | Overview | Overview and Setup");
                    #endregion
                }
                return this.mUIAbilalogoimageImage;
            }
        }
        #endregion
        
        #region Fields
        private HtmlImage mUIAbilalogoimageImage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIAddIndividualDocument : HtmlDocument
    {
        
        public UIAddIndividualDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = "BodyTag";
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Add - Individual";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/iWeb/Forms/DynamicEdit.aspx";
            //this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://nf.testacfe.com/iWeb/Forms/DynamicEdit.aspx?Action=Add&FormKey=25cad8ad-0" +
            //    "921-4b50-92ed-f8d36f1fad7f&ItemKey=649d1a9d-ca93-4dd8-b5b5-aa00e10946b0&tab=crm&" +
            //    "tabitem=individuals";
            this.WindowTitles.Add("Add - Individual");
            #endregion
        }
        
        #region Properties
        public HtmlComboBox UIInd_prf_codeComboBox
        {
            get
            {
                if ((this.mUIInd_prf_codeComboBox == null))
                {
                    this.mUIInd_prf_codeComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUIInd_prf_codeComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "ind_prf_code";
                    this.mUIInd_prf_codeComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = "ind_prf_code";
                    this.mUIInd_prf_codeComboBox.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = null;
                    this.mUIInd_prf_codeComboBox.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mUIInd_prf_codeComboBox.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mUIInd_prf_codeComboBox.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "14";
                    this.mUIInd_prf_codeComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = "DataFormDropDownList";
                    this.mUIInd_prf_codeComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "name=\"ind_prf_code\" tabindex=\"1\" class=\"";
                    this.mUIInd_prf_codeComboBox.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "24";
                    this.mUIInd_prf_codeComboBox.WindowTitles.Add("Add - Individual");
                    #endregion
                }
                return this.mUIInd_prf_codeComboBox;
            }
        }
        
        public HtmlEdit UIFirstnameEdit
        {
            get
            {
                if ((this.mUIFirstnameEdit == null))
                {
                    this.mUIFirstnameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIFirstnameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "ind_first_name";
                    this.mUIFirstnameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "ind_first_name";
                    this.mUIFirstnameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "first name:";
                    this.mUIFirstnameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIFirstnameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = "first name";
                    this.mUIFirstnameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "DataFormTextBox";
                    this.mUIFirstnameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"ind_first_name\" tabindex=\"2\" title";
                    this.mUIFirstnameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "11";
                    this.mUIFirstnameEdit.WindowTitles.Add("Add - Individual");
                    #endregion
                }
                return this.mUIFirstnameEdit;
            }
        }
        
        public HtmlEdit UILastnameEdit
        {
            get
            {
                if ((this.mUILastnameEdit == null))
                {
                    this.mUILastnameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUILastnameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "ind_last_name";
                    this.mUILastnameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "ind_last_name";
                    this.mUILastnameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUILastnameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUILastnameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = "last name";
                    this.mUILastnameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "DataFormTextBox";
                    this.mUILastnameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"ind_last_name\" tabindex=\"4\" title=";
                    this.mUILastnameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "57";
                    this.mUILastnameEdit.WindowTitles.Add("Add - Individual");
                    #endregion
                }
                return this.mUILastnameEdit;
            }
        }
        
        public HtmlComboBox UIIndividualtypeComboBox
        {
            get
            {
                if ((this.mUIIndividualtypeComboBox == null))
                {
                    this.mUIIndividualtypeComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUIIndividualtypeComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "ind_int_code";
                    this.mUIIndividualtypeComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = "ind_int_code";
                    this.mUIIndividualtypeComboBox.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = "individual type:";
                    this.mUIIndividualtypeComboBox.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mUIIndividualtypeComboBox.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mUIIndividualtypeComboBox.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "6";
                    this.mUIIndividualtypeComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = "DataFormDropDownList";
                    this.mUIIndividualtypeComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "name=\"ind_int_code\" tabindex=\"9\" class=\"";
                    this.mUIIndividualtypeComboBox.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "22";
                    this.mUIIndividualtypeComboBox.WindowTitles.Add("Add - Individual");
                    #endregion
                }
                return this.mUIIndividualtypeComboBox;
            }
        }
        
        public HtmlEdit UITitleEdit
        {
            get
            {
                if ((this.mUITitleEdit == null))
                {
                    this.mUITitleEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUITitleEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "ixo_title";
                    this.mUITitleEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "ixo_title";
                    this.mUITitleEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "title:";
                    this.mUITitleEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUITitleEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = "title";
                    this.mUITitleEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "DataFormTextBox";
                    this.mUITitleEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"ixo_title\" tabindex=\"11\" title=\"ti";
                    this.mUITitleEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "56";
                    this.mUITitleEdit.WindowTitles.Add("Add - Individual");
                    #endregion
                }
                return this.mUITitleEdit;
            }
        }
        
        public HtmlEdit UIEmailaddressEdit
        {
            get
            {
                if ((this.mUIEmailaddressEdit == null))
                {
                    this.mUIEmailaddressEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIEmailaddressEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "eml_address";
                    this.mUIEmailaddressEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "eml_address";
                    this.mUIEmailaddressEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "e-mail:";
                    this.mUIEmailaddressEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIEmailaddressEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = "e-mail address";
                    this.mUIEmailaddressEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "DataFormTextBox";
                    this.mUIEmailaddressEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"eml_address\" tabindex=\"13\" title=\"";
                    this.mUIEmailaddressEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "62";
                    this.mUIEmailaddressEdit.WindowTitles.Add("Add - Individual");
                    #endregion
                }
                return this.mUIEmailaddressEdit;
            }
        }
        
        public HtmlEdit UIAddressline1Edit
        {
            get
            {
                if ((this.mUIAddressline1Edit == null))
                {
                    this.mUIAddressline1Edit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIAddressline1Edit.SearchProperties[HtmlEdit.PropertyNames.Id] = "adr_line1";
                    this.mUIAddressline1Edit.SearchProperties[HtmlEdit.PropertyNames.Name] = "adr_line1";
                    this.mUIAddressline1Edit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "address lines:";
                    this.mUIAddressline1Edit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIAddressline1Edit.FilterProperties[HtmlEdit.PropertyNames.Title] = "address line 1";
                    this.mUIAddressline1Edit.FilterProperties[HtmlEdit.PropertyNames.Class] = "DataFormTextBox";
                    this.mUIAddressline1Edit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"adr_line1\" tabindex=\"31\" title=\"ad";
                    this.mUIAddressline1Edit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "19";
                    this.mUIAddressline1Edit.WindowTitles.Add("Add - Individual");
                    #endregion
                }
                return this.mUIAddressline1Edit;
            }
        }
        
        public HtmlEdit UIAddressline1Edit1
        {
            get
            {
                if ((this.mUIAddressline1Edit1 == null))
                {
                    this.mUIAddressline1Edit1 = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIAddressline1Edit1.SearchProperties[HtmlEdit.PropertyNames.Id] = "adr_line1";
                    this.mUIAddressline1Edit1.SearchProperties[HtmlEdit.PropertyNames.Name] = "adr_line1";
                    this.mUIAddressline1Edit1.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "address lines:";
                    this.mUIAddressline1Edit1.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIAddressline1Edit1.FilterProperties[HtmlEdit.PropertyNames.Title] = "address line 1";
                    this.mUIAddressline1Edit1.FilterProperties[HtmlEdit.PropertyNames.Class] = "DataFormTextBox";
                    this.mUIAddressline1Edit1.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"adr_line1\" tabindex=\"31\" title=\"ad";
                    this.mUIAddressline1Edit1.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "13";
                    this.mUIAddressline1Edit1.WindowTitles.Add("Add - Individual");
                    #endregion
                }
                return this.mUIAddressline1Edit1;
            }
        }
        
        public HtmlEdit UIAddressline2Edit
        {
            get
            {
                if ((this.mUIAddressline2Edit == null))
                {
                    this.mUIAddressline2Edit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIAddressline2Edit.SearchProperties[HtmlEdit.PropertyNames.Id] = "adr_line2";
                    this.mUIAddressline2Edit.SearchProperties[HtmlEdit.PropertyNames.Name] = "adr_line2";
                    this.mUIAddressline2Edit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIAddressline2Edit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIAddressline2Edit.FilterProperties[HtmlEdit.PropertyNames.Title] = "address line 2";
                    this.mUIAddressline2Edit.FilterProperties[HtmlEdit.PropertyNames.Class] = "DataFormTextBox";
                    this.mUIAddressline2Edit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"adr_line2\" tabindex=\"32\" title=\"ad";
                    this.mUIAddressline2Edit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "14";
                    this.mUIAddressline2Edit.WindowTitles.Add("Add - Individual");
                    #endregion
                }
                return this.mUIAddressline2Edit;
            }
        }
        
        public HtmlEdit UICityEdit
        {
            get
            {
                if ((this.mUICityEdit == null))
                {
                    this.mUICityEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUICityEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "adr_city";
                    this.mUICityEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "adr_city";
                    this.mUICityEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "city/state/zip:";
                    this.mUICityEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUICityEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = "city";
                    this.mUICityEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "DataFormTextBox";
                    this.mUICityEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"adr_city\" tabindex=\"34\" title=\"cit";
                    this.mUICityEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "16";
                    this.mUICityEdit.WindowTitles.Add("Add - Individual");
                    #endregion
                }
                return this.mUICityEdit;
            }
        }
        
        public HtmlComboBox UIAdr_stateComboBox
        {
            get
            {
                if ((this.mUIAdr_stateComboBox == null))
                {
                    this.mUIAdr_stateComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUIAdr_stateComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "adr_state";
                    this.mUIAdr_stateComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = "adr_state";
                    this.mUIAdr_stateComboBox.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = null;
                    this.mUIAdr_stateComboBox.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mUIAdr_stateComboBox.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mUIAdr_stateComboBox.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "60";
                    this.mUIAdr_stateComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = "DataFormDropDownList";
                    this.mUIAdr_stateComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "name=\"adr_state\" tabindex=\"35\" class=\"Da";
                    this.mUIAdr_stateComboBox.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "13";
                    this.mUIAdr_stateComboBox.WindowTitles.Add("Add - Individual");
                    #endregion
                }
                return this.mUIAdr_stateComboBox;
            }
        }
        
        public HtmlEdit UIPostalcodeEdit
        {
            get
            {
                if ((this.mUIPostalcodeEdit == null))
                {
                    this.mUIPostalcodeEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPostalcodeEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "adr_post_code";
                    this.mUIPostalcodeEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "adr_post_code";
                    this.mUIPostalcodeEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIPostalcodeEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIPostalcodeEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = "postal code";
                    this.mUIPostalcodeEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "DataFormTextBox";
                    this.mUIPostalcodeEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"adr_post_code\" tabindex=\"36\" title";
                    this.mUIPostalcodeEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "17";
                    this.mUIPostalcodeEdit.WindowTitles.Add("Add - Individual");
                    #endregion
                }
                return this.mUIPostalcodeEdit;
            }
        }
        
        public HtmlEdit UICountyEdit
        {
            get
            {
                if ((this.mUICountyEdit == null))
                {
                    this.mUICountyEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUICountyEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "adr_county";
                    this.mUICountyEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "adr_county";
                    this.mUICountyEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "county/district:";
                    this.mUICountyEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUICountyEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = "county";
                    this.mUICountyEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "DataFormTextBox";
                    this.mUICountyEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"adr_county\" tabindex=\"37\" title=\"c";
                    this.mUICountyEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "18";
                    this.mUICountyEdit.WindowTitles.Add("Add - Individual");
                    #endregion
                }
                return this.mUICountyEdit;
            }
        }
        
        public HtmlComboBox UICountryComboBox
        {
            get
            {
                if ((this.mUICountryComboBox == null))
                {
                    this.mUICountryComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUICountryComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "adr_country";
                    this.mUICountryComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = "adr_country";
                    this.mUICountryComboBox.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = "country:";
                    this.mUICountryComboBox.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mUICountryComboBox.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mUICountryComboBox.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "240";
                    this.mUICountryComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = "DataFormDropDownList";
                    this.mUICountryComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "name=\"adr_country\" tabindex=\"29\" class=\"";
                    this.mUICountryComboBox.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "10";
                    this.mUICountryComboBox.WindowTitles.Add("Add - Individual");
                    #endregion
                }
                return this.mUICountryComboBox;
            }
        }
        
        public HtmlDiv UIDesignedDivPane
        {
            get
            {
                if ((this.mUIDesignedDivPane == null))
                {
                    this.mUIDesignedDivPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIDesignedDivPane.SearchProperties[HtmlDiv.PropertyNames.Id] = "DesignedDiv";
                    this.mUIDesignedDivPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIDesignedDivPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "select from org:\r\nclick on icon to searc";
                    this.mUIDesignedDivPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIDesignedDivPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "DataFormDivDefault";
                    this.mUIDesignedDivPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"DataFormDivDefault\" id=\"DesignedDiv\" style=\"width: 916px; height: 736px; p" +
                        "osition: relative;\"";
                    this.mUIDesignedDivPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "19";
                    this.mUIDesignedDivPane.WindowTitles.Add("Add - Individual");
                    #endregion
                }
                return this.mUIDesignedDivPane;
            }
        }
        
        public HtmlComboBox UICfx_fxt_keyComboBox
        {
            get
            {
                if ((this.mUICfx_fxt_keyComboBox == null))
                {
                    this.mUICfx_fxt_keyComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUICfx_fxt_keyComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "cfx_fxt_key";
                    this.mUICfx_fxt_keyComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = "cfx_fxt_key";
                    this.mUICfx_fxt_keyComboBox.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = null;
                    this.mUICfx_fxt_keyComboBox.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mUICfx_fxt_keyComboBox.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mUICfx_fxt_keyComboBox.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "4";
                    this.mUICfx_fxt_keyComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = "DataFormDropDownList";
                    this.mUICfx_fxt_keyComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "name=\"cfx_fxt_key\" tabindex=\"89\" class=\"";
                    this.mUICfx_fxt_keyComboBox.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "12";
                    this.mUICfx_fxt_keyComboBox.WindowTitles.Add("Add - Individual");
                    #endregion
                }
                return this.mUICfx_fxt_keyComboBox;
            }
        }
        
        public HtmlEdit UIPhonenumberEdit
        {
            get
            {
                if ((this.mUIPhonenumberEdit == null))
                {
                    this.mUIPhonenumberEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPhonenumberEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "phn_number";
                    this.mUIPhonenumberEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "phn_number";
                    this.mUIPhonenumberEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "number:";
                    this.mUIPhonenumberEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIPhonenumberEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = "phone number";
                    this.mUIPhonenumberEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "DataFormTextBox";
                    this.mUIPhonenumberEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"phn_number\" tabindex=\"86\" title=\"p";
                    this.mUIPhonenumberEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "64";
                    this.mUIPhonenumberEdit.WindowTitles.Add("Add - Individual");
                    #endregion
                }
                return this.mUIPhonenumberEdit;
            }
        }
        
        public HtmlComboBox UIContactbyComboBox
        {
            get
            {
                if ((this.mUIContactbyComboBox == null))
                {
                    this.mUIContactbyComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUIContactbyComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "cst_pref_comm_meth";
                    this.mUIContactbyComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = "cst_pref_comm_meth";
                    this.mUIContactbyComboBox.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = "contact by: ";
                    this.mUIContactbyComboBox.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mUIContactbyComboBox.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mUIContactbyComboBox.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "5";
                    this.mUIContactbyComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = "DataFormDropDownList";
                    this.mUIContactbyComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "name=\"cst_pref_comm_meth\" tabindex=\"100\"";
                    this.mUIContactbyComboBox.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "25";
                    this.mUIContactbyComboBox.WindowTitles.Add("Add - Individual");
                    #endregion
                }
                return this.mUIContactbyComboBox;
            }
        }
        
        public HtmlCheckBox UIPhoneCheckBox
        {
            get
            {
                if ((this.mUIPhoneCheckBox == null))
                {
                    this.mUIPhoneCheckBox = new HtmlCheckBox(this);
                    #region Search Criteria
                    this.mUIPhoneCheckBox.SearchProperties[HtmlCheckBox.PropertyNames.Id] = "cst_no_phone_flag";
                    this.mUIPhoneCheckBox.SearchProperties[HtmlCheckBox.PropertyNames.Name] = "cst_no_phone_flag";
                    this.mUIPhoneCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.Value] = "on";
                    this.mUIPhoneCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.LabeledBy] = "phone";
                    this.mUIPhoneCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.Title] = null;
                    this.mUIPhoneCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.Class] = null;
                    this.mUIPhoneCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.ControlDefinition] = "name=\"cst_no_phone_flag\" tabindex=\"102\" ";
                    this.mUIPhoneCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.TagInstance] = "35";
                    this.mUIPhoneCheckBox.WindowTitles.Add("Add - Individual");
                    #endregion
                }
                return this.mUIPhoneCheckBox;
            }
        }
        
        public HtmlComboBox UIKeyComboBox
        {
            get
            {
                if ((this.mUIKeyComboBox == null))
                {
                    this.mUIKeyComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUIKeyComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "cx2__cxa_adt_key";
                    this.mUIKeyComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = "cx2__cxa_adt_key";
                    this.mUIKeyComboBox.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = null;
                    this.mUIKeyComboBox.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mUIKeyComboBox.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mUIKeyComboBox.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "5";
                    this.mUIKeyComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = "DataFormDropDownList";
                    this.mUIKeyComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "name=\"cx2__cxa_adt_key\" tabindex=\"52\" cl";
                    this.mUIKeyComboBox.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "11";
                    this.mUIKeyComboBox.WindowTitles.Add("Add - Individual");
                    #endregion
                }
                return this.mUIKeyComboBox;
            }
        }
        
        public HtmlEdit UIAddressline1Edit2
        {
            get
            {
                if ((this.mUIAddressline1Edit2 == null))
                {
                    this.mUIAddressline1Edit2 = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIAddressline1Edit2.SearchProperties[HtmlEdit.PropertyNames.Id] = "ad2__adr_line1";
                    this.mUIAddressline1Edit2.SearchProperties[HtmlEdit.PropertyNames.Name] = "ad2__adr_line1";
                    this.mUIAddressline1Edit2.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "address lines:";
                    this.mUIAddressline1Edit2.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIAddressline1Edit2.FilterProperties[HtmlEdit.PropertyNames.Title] = "address line 1";
                    this.mUIAddressline1Edit2.FilterProperties[HtmlEdit.PropertyNames.Class] = "DataFormTextBox";
                    this.mUIAddressline1Edit2.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"ad2__adr_line1\" tabindex=\"61\" titl";
                    this.mUIAddressline1Edit2.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "23";
                    this.mUIAddressline1Edit2.WindowTitles.Add("Add - Individual");
                    #endregion
                }
                return this.mUIAddressline1Edit2;
            }
        }
        
        public HtmlEdit UICityEdit1
        {
            get
            {
                if ((this.mUICityEdit1 == null))
                {
                    this.mUICityEdit1 = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUICityEdit1.SearchProperties[HtmlEdit.PropertyNames.Id] = "ad2__adr_city";
                    this.mUICityEdit1.SearchProperties[HtmlEdit.PropertyNames.Name] = "ad2__adr_city";
                    this.mUICityEdit1.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "city/state/zip:";
                    this.mUICityEdit1.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUICityEdit1.FilterProperties[HtmlEdit.PropertyNames.Title] = "city";
                    this.mUICityEdit1.FilterProperties[HtmlEdit.PropertyNames.Class] = "DataFormTextBox";
                    this.mUICityEdit1.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"ad2__adr_city\" tabindex=\"64\" title";
                    this.mUICityEdit1.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "26";
                    this.mUICityEdit1.WindowTitles.Add("Add - Individual");
                    #endregion
                }
                return this.mUICityEdit1;
            }
        }
        
        public HtmlComboBox UIAd2__adr_stateComboBox
        {
            get
            {
                if ((this.mUIAd2__adr_stateComboBox == null))
                {
                    this.mUIAd2__adr_stateComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUIAd2__adr_stateComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "ad2__adr_state";
                    this.mUIAd2__adr_stateComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = "ad2__adr_state";
                    this.mUIAd2__adr_stateComboBox.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = null;
                    this.mUIAd2__adr_stateComboBox.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mUIAd2__adr_stateComboBox.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mUIAd2__adr_stateComboBox.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "60";
                    this.mUIAd2__adr_stateComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = "DataFormDropDownList";
                    this.mUIAd2__adr_stateComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "name=\"ad2__adr_state\" tabindex=\"65\" clas";
                    this.mUIAd2__adr_stateComboBox.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "14";
                    this.mUIAd2__adr_stateComboBox.WindowTitles.Add("Add - Individual");
                    #endregion
                }
                return this.mUIAd2__adr_stateComboBox;
            }
        }
        
        public HtmlDiv UIDesignedSubDiv_DESIGPane
        {
            get
            {
                if ((this.mUIDesignedSubDiv_DESIGPane == null))
                {
                    this.mUIDesignedSubDiv_DESIGPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIDesignedSubDiv_DESIGPane.SearchProperties[HtmlDiv.PropertyNames.Id] = "DesignedSubDiv_DESIGNEDSUBFORM_1";
                    this.mUIDesignedSubDiv_DESIGPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIDesignedSubDiv_DESIGPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "address lines:city/state/zip: Please sel";
                    this.mUIDesignedSubDiv_DESIGPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIDesignedSubDiv_DESIGPane.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mUIDesignedSubDiv_DESIGPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"DesignedSubDiv_DESIGNEDSUBFORM_1\" style=\"width: 406px; height: 139px; positio" +
                        "n: relative;\"";
                    this.mUIDesignedSubDiv_DESIGPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "28";
                    this.mUIDesignedSubDiv_DESIGPane.WindowTitles.Add("Add - Individual");
                    #endregion
                }
                return this.mUIDesignedSubDiv_DESIGPane;
            }
        }
        
        public HtmlEdit UIPostalcodeEdit1
        {
            get
            {
                if ((this.mUIPostalcodeEdit1 == null))
                {
                    this.mUIPostalcodeEdit1 = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPostalcodeEdit1.SearchProperties[HtmlEdit.PropertyNames.Id] = "ad2__adr_post_code";
                    this.mUIPostalcodeEdit1.SearchProperties[HtmlEdit.PropertyNames.Name] = "ad2__adr_post_code";
                    this.mUIPostalcodeEdit1.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIPostalcodeEdit1.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIPostalcodeEdit1.FilterProperties[HtmlEdit.PropertyNames.Title] = "postal code";
                    this.mUIPostalcodeEdit1.FilterProperties[HtmlEdit.PropertyNames.Class] = "DataFormTextBox";
                    this.mUIPostalcodeEdit1.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"ad2__adr_post_code\" tabindex=\"66\" ";
                    this.mUIPostalcodeEdit1.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "27";
                    this.mUIPostalcodeEdit1.WindowTitles.Add("Add - Individual");
                    #endregion
                }
                return this.mUIPostalcodeEdit1;
            }
        }
        
        public HtmlEdit UICountyEdit1
        {
            get
            {
                if ((this.mUICountyEdit1 == null))
                {
                    this.mUICountyEdit1 = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUICountyEdit1.SearchProperties[HtmlEdit.PropertyNames.Id] = "ad2__adr_county";
                    this.mUICountyEdit1.SearchProperties[HtmlEdit.PropertyNames.Name] = "ad2__adr_county";
                    this.mUICountyEdit1.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "county/district:";
                    this.mUICountyEdit1.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUICountyEdit1.FilterProperties[HtmlEdit.PropertyNames.Title] = "county";
                    this.mUICountyEdit1.FilterProperties[HtmlEdit.PropertyNames.Class] = "DataFormTextBox";
                    this.mUICountyEdit1.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"ad2__adr_county\" tabindex=\"67\" tit";
                    this.mUICountyEdit1.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "28";
                    this.mUICountyEdit1.WindowTitles.Add("Add - Individual");
                    #endregion
                }
                return this.mUICountyEdit1;
            }
        }
        
        public HtmlComboBox UICountryComboBox1
        {
            get
            {
                if ((this.mUICountryComboBox1 == null))
                {
                    this.mUICountryComboBox1 = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUICountryComboBox1.SearchProperties[HtmlComboBox.PropertyNames.Id] = "ad2__adr_country";
                    this.mUICountryComboBox1.SearchProperties[HtmlComboBox.PropertyNames.Name] = "ad2__adr_country";
                    this.mUICountryComboBox1.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = "country:";
                    this.mUICountryComboBox1.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mUICountryComboBox1.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mUICountryComboBox1.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "240";
                    this.mUICountryComboBox1.FilterProperties[HtmlComboBox.PropertyNames.Class] = "DataFormDropDownList";
                    this.mUICountryComboBox1.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "name=\"ad2__adr_country\" tabindex=\"59\" cl";
                    this.mUICountryComboBox1.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "23";
                    this.mUICountryComboBox1.WindowTitles.Add("Add - Individual");
                    #endregion
                }
                return this.mUICountryComboBox1;
            }
        }
        
        public HtmlSpan UICst_regexPane
        {
            get
            {
                if ((this.mUICst_regexPane == null))
                {
                    this.mUICst_regexPane = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUICst_regexPane.SearchProperties[HtmlDiv.PropertyNames.Id] = "cst_regex";
                    this.mUICst_regexPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUICst_regexPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "ACFE Customer Password Requirements";
                    this.mUICst_regexPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUICst_regexPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "DataFormLabel";
                    this.mUICst_regexPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"DataFormLabel\" id=\"cst_regex\" style=\"left: 631px; top: 625px; height: 13px" +
                        "; position: absolute;\"";
                    this.mUICst_regexPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "115";
                    this.mUICst_regexPane.WindowTitles.Add("Add - Individual");
                    #endregion
                }
                return this.mUICst_regexPane;
            }
        }
        
        public HtmlComboBox UITypeComboBox
        {
            get
            {
                if ((this.mUITypeComboBox == null))
                {
                    this.mUITypeComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUITypeComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "cp2__cph_pht_key";
                    this.mUITypeComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = "cp2__cph_pht_key";
                    this.mUITypeComboBox.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = "type:";
                    this.mUITypeComboBox.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mUITypeComboBox.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mUITypeComboBox.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "7";
                    this.mUITypeComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = "DataFormDropDownList";
                    this.mUITypeComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "name=\"cp2__cph_pht_key\" tabindex=\"94\" cl";
                    this.mUITypeComboBox.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "8";
                    this.mUITypeComboBox.WindowTitles.Add("Add - Individual");
                    #endregion
                }
                return this.mUITypeComboBox;
            }
        }
        
        public HtmlEdit UIPhonenumberEdit1
        {
            get
            {
                if ((this.mUIPhonenumberEdit1 == null))
                {
                    this.mUIPhonenumberEdit1 = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPhonenumberEdit1.SearchProperties[HtmlEdit.PropertyNames.Id] = "ph2__phn_number";
                    this.mUIPhonenumberEdit1.SearchProperties[HtmlEdit.PropertyNames.Name] = "ph2__phn_number";
                    this.mUIPhonenumberEdit1.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "number:";
                    this.mUIPhonenumberEdit1.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIPhonenumberEdit1.FilterProperties[HtmlEdit.PropertyNames.Title] = "phone number";
                    this.mUIPhonenumberEdit1.FilterProperties[HtmlEdit.PropertyNames.Class] = "DataFormTextBox";
                    this.mUIPhonenumberEdit1.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"ph2__phn_number\" tabindex=\"95\" tit";
                    this.mUIPhonenumberEdit1.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "59";
                    this.mUIPhonenumberEdit1.WindowTitles.Add("Add - Individual");
                    #endregion
                }
                return this.mUIPhonenumberEdit1;
            }
        }
        
        public HtmlEdit UINewpasswordEdit
        {
            get
            {
                if ((this.mUINewpasswordEdit == null))
                {
                    this.mUINewpasswordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUINewpasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "cst_new_password";
                    this.mUINewpasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "cst_new_password";
                    this.mUINewpasswordEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "password:";
                    this.mUINewpasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUINewpasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = "new password";
                    this.mUINewpasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "DataFormTextBox";
                    this.mUINewpasswordEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"cst_new_password\" tabindex=\"106\" t";
                    this.mUINewpasswordEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "10";
                    this.mUINewpasswordEdit.WindowTitles.Add("Add - Individual");
                    #endregion
                }
                return this.mUINewpasswordEdit;
            }
        }
        
        public HtmlEdit UIConfirmnewpasswordEdit
        {
            get
            {
                if ((this.mUIConfirmnewpasswordEdit == null))
                {
                    this.mUIConfirmnewpasswordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIConfirmnewpasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "cst_new_password_confirm";
                    this.mUIConfirmnewpasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "cst_new_password_confirm";
                    this.mUIConfirmnewpasswordEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "confirm password:";
                    this.mUIConfirmnewpasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIConfirmnewpasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = "confirm new password";
                    this.mUIConfirmnewpasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "DataFormTextBox";
                    this.mUIConfirmnewpasswordEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"cst_new_password_confirm\" tabindex";
                    this.mUIConfirmnewpasswordEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "60";
                    this.mUIConfirmnewpasswordEdit.WindowTitles.Add("Add - Individual");
                    #endregion
                }
                return this.mUIConfirmnewpasswordEdit;
            }
        }
        
        public HtmlCheckBox UIForceusertochangepasCheckBox
        {
            get
            {
                if ((this.mUIForceusertochangepasCheckBox == null))
                {
                    this.mUIForceusertochangepasCheckBox = new HtmlCheckBox(this);
                    #region Search Criteria
                    this.mUIForceusertochangepasCheckBox.SearchProperties[HtmlCheckBox.PropertyNames.Id] = "cst_web_force_password_change";
                    this.mUIForceusertochangepasCheckBox.SearchProperties[HtmlCheckBox.PropertyNames.Name] = "cst_web_force_password_change";
                    this.mUIForceusertochangepasCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.Value] = "on";
                    this.mUIForceusertochangepasCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.LabeledBy] = "force user to change password?";
                    this.mUIForceusertochangepasCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.Title] = null;
                    this.mUIForceusertochangepasCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.Class] = null;
                    this.mUIForceusertochangepasCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.ControlDefinition] = "name=\"cst_web_force_password_change\" tab";
                    this.mUIForceusertochangepasCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.TagInstance] = "52";
                    this.mUIForceusertochangepasCheckBox.WindowTitles.Add("Add - Individual");
                    #endregion
                }
                return this.mUIForceusertochangepasCheckBox;
            }
        }
        
        public HtmlInputButton UISaveButton
        {
            get
            {
                if ((this.mUISaveButton == null))
                {
                    this.mUISaveButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUISaveButton.SearchProperties[HtmlButton.PropertyNames.Id] = "ButtonSave";
                    this.mUISaveButton.SearchProperties[HtmlButton.PropertyNames.Name] = "ButtonSave";
                    this.mUISaveButton.FilterProperties[HtmlButton.PropertyNames.DisplayText] = "Save";
                    this.mUISaveButton.FilterProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUISaveButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUISaveButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-primary";
                    this.mUISaveButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "name=\"ButtonSave\" class=\"btn btn-primary";
                    this.mUISaveButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "69";
                    this.mUISaveButton.WindowTitles.Add("Add - Individual");
                    #endregion
                }
                return this.mUISaveButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlComboBox mUIInd_prf_codeComboBox;
        
        private HtmlEdit mUIFirstnameEdit;
        
        private HtmlEdit mUILastnameEdit;
        
        private HtmlComboBox mUIIndividualtypeComboBox;
        
        private HtmlEdit mUITitleEdit;
        
        private HtmlEdit mUIEmailaddressEdit;
        
        private HtmlEdit mUIAddressline1Edit;
        
        private HtmlEdit mUIAddressline1Edit1;
        
        private HtmlEdit mUIAddressline2Edit;
        
        private HtmlEdit mUICityEdit;
        
        private HtmlComboBox mUIAdr_stateComboBox;
        
        private HtmlEdit mUIPostalcodeEdit;
        
        private HtmlEdit mUICountyEdit;
        
        private HtmlComboBox mUICountryComboBox;
        
        private HtmlDiv mUIDesignedDivPane;
        
        private HtmlComboBox mUICfx_fxt_keyComboBox;
        
        private HtmlEdit mUIPhonenumberEdit;
        
        private HtmlComboBox mUIContactbyComboBox;
        
        private HtmlCheckBox mUIPhoneCheckBox;
        
        private HtmlComboBox mUIKeyComboBox;
        
        private HtmlEdit mUIAddressline1Edit2;
        
        private HtmlEdit mUICityEdit1;
        
        private HtmlComboBox mUIAd2__adr_stateComboBox;
        
        private HtmlDiv mUIDesignedSubDiv_DESIGPane;
        
        private HtmlEdit mUIPostalcodeEdit1;
        
        private HtmlEdit mUICountyEdit1;
        
        private HtmlComboBox mUICountryComboBox1;
        
        private HtmlSpan mUICst_regexPane;
        
        private HtmlComboBox mUITypeComboBox;
        
        private HtmlEdit mUIPhonenumberEdit1;
        
        private HtmlEdit mUINewpasswordEdit;
        
        private HtmlEdit mUIConfirmnewpasswordEdit;
        
        private HtmlCheckBox mUIForceusertochangepasCheckBox;
        
        private HtmlInputButton mUISaveButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UICRMIndividualsMrRyanDocument : HtmlDocument
    {
        
        public UICRMIndividualsMrRyanDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = "BodyTag";
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "CRM | Individuals | Mr. Ryan Bingham";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/iWeb/Forms/DynamicProfile.aspx";
            //this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://nf.testacfe.com/iWeb/Forms/DynamicProfile.aspx?FormKey=b772881d-d704-40f3" +
            //    "-92b6-09b13a50fcc9&ItemKey=649d1a9d-ca93-4dd8-b5b5-aa00e10946b0&key=ed6fea02-8d0" +
            //    "7-46c2-a77a-bf1838ed39c5";
            this.WindowTitles.Add("CRM | Individuals | Mr. Ryan Bingham");
            #endregion
        }
        
        #region Properties
        public HtmlSpan UIF1_cxa_mailing_labelPane
        {
            get
            {
                if ((this.mUIF1_cxa_mailing_labelPane == null))
                {
                    this.mUIF1_cxa_mailing_labelPane = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUIF1_cxa_mailing_labelPane.SearchProperties[HtmlDiv.PropertyNames.Id] = "F1_cxa_mailing_label_html";
                    this.mUIF1_cxa_mailing_labelPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIF1_cxa_mailing_labelPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Mr. Ryan Bingham\r\n1234 Test St\r\nAustin, ";
                    this.mUIF1_cxa_mailing_labelPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIF1_cxa_mailing_labelPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "DataFormTextBox";
                    this.mUIF1_cxa_mailing_labelPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"DataFormTextBox\" id=\"F1_cxa_mailing_label_html\" style=\"left: 12px; top: 41" +
                        "px; width: 394px; height: 82px; position: absolute;\" displayashtml_tag=\"500\"";
                    this.mUIF1_cxa_mailing_labelPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "49";
                    this.mUIF1_cxa_mailing_labelPane.WindowTitles.Add("CRM | Individuals | Mr. Ryan Bingham");
                    #endregion
                }
                return this.mUIF1_cxa_mailing_labelPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlSpan mUIF1_cxa_mailing_labelPane;
        #endregion
    }
}
